export const MY_BETS_DATA = {
  bets: [
    [
      {
        type: 'soccer',
        teams: ['Queens Park Rangers', 'AFC Bournemouth'],
        wagered: 12,
        on: 'AFC Bournemouth',
        odd: 1.23,
        time: '23:25 11.06.2022',
        isWin: false,
      },
      {
        type: 'football',
        teams: ['Queens Park Rangers', 'AFC Bournemouth'],
        wagered: 12,
        on: 'AFC Bournemouth',
        odd: 1.23,
        time: '23:25 11.06.2022',
        isWin: false,
      },
    ],
    [
      {
        type: 'soccer',
        teams: ['Queens Park Rangers', 'AFC Bournemouth'],
        wagered: 12,
        on: 'AFC Bournemouth',
        odd: 1.23,
        time: '23:25 11.06.2022',
        isWin: true,
      },
      {
        type: 'soccer',
        teams: ['Queens Park Rangers', 'AFC Bournemouth'],
        wagered: 12,
        on: 'AFC Bournemouth',
        odd: 1.23,
        time: '23:25 11.06.2022',
        isWin: false,
      },
      {
        type: 'soccer',
        teams: ['Queens Park Rangers', 'AFC Bournemouth'],
        wagered: 12,
        on: 'AFC Bournemouth',
        odd: 1.23,
        time: '23:25 11.06.2022',
        isWin: true,
      },
      {
        type: 'soccer',
        teams: ['Queens Park Rangers', 'AFC Bournemouth'],
        wagered: 12,
        on: 'AFC Bournemouth',
        odd: 1.23,
        time: '23:25 11.06.2022',
        isWin: false,
      },
    ],
    [
      {
        type: 'soccer',
        teams: ['Queens Park Rangers', 'AFC Bournemouth'],
        wagered: 12,
        on: 'AFC Bournemouth',
        odd: 1.23,
        time: '23:25 11.06.2022',
        isWin: false,
      },
      {
        type: 'football',
        teams: ['Queens Park Rangers', 'AFC Bournemouth'],
        wagered: 12,
        on: 'AFC Bournemouth',
        odd: 1.23,
        time: '23:25 11.06.2022',
        isWin: false,
      },
      {
        type: 'football',
        teams: ['Queens Park Rangers', 'AFC Bournemouth'],
        wagered: 12,
        on: 'AFC Bournemouth',
        odd: 1.23,
        time: '23:25 11.06.2022',
        isWin: false,
      },
      {
        type: 'soccer',
        teams: ['Queens Park Rangers', 'AFC Bournemouth'],
        wagered: 12,
        on: 'AFC Bournemouth',
        odd: 1.23,
        time: '23:25 11.06.2022',
        isWin: false,
      },
      {
        type: 'football',
        teams: ['Queens Park Rangers', 'AFC Bournemouth'],
        wagered: 12,
        on: 'AFC Bournemouth',
        odd: 1.23,
        time: '23:25 11.06.2022',
        isWin: false,
      },
    ],
    [
      {
        type: 'soccer',
        teams: ['Queens Park Rangers', 'AFC Bournemouth'],
        wagered: 12,
        on: 'AFC Bournemouth',
        odd: 1.23,
        time: '23:25 11.06.2022',
        isWin: false,
      },
      {
        type: 'football',
        teams: ['Queens Park Rangers', 'AFC Bournemouth'],
        wagered: 12,
        on: 'AFC Bournemouth',
        odd: 1.23,
        time: '23:25 11.06.2022',
        isWin: false,
      },
      {
        type: 'football',
        teams: ['Queens Park Rangers', 'AFC Bournemouth'],
        wagered: 12,
        on: 'AFC Bournemouth',
        odd: 1.23,
        time: '23:25 11.06.2022',
        isWin: false,
      },
      {
        type: 'soccer',
        teams: ['Queens Park Rangers', 'AFC Bournemouth'],
        wagered: 12,
        on: 'AFC Bournemouth',
        odd: 1.23,
        time: '23:25 11.06.2022',
        isWin: false,
      },
      {
        type: 'football',
        teams: ['Queens Park Rangers', 'AFC Bournemouth'],
        wagered: 12,
        on: 'AFC Bournemouth',
        odd: 1.23,
        time: '23:25 11.06.2022',
        isWin: false,
      },
    ],
    [
      {
        type: 'soccer',
        teams: ['Queens Park Rangers', 'AFC Bournemouth'],
        wagered: 12,
        on: 'AFC Bournemouth',
        odd: 1.23,
        time: '23:25 11.06.2022',
        isWin: true,
      },
      {
        type: 'soccer',
        teams: ['Queens Park Rangers', 'AFC Bournemouth'],
        wagered: 12,
        on: 'AFC Bournemouth',
        odd: 1.23,
        time: '23:25 11.06.2022',
        isWin: false,
      },
      {
        type: 'soccer',
        teams: ['Queens Park Rangers', 'AFC Bournemouth'],
        wagered: 12,
        on: 'AFC Bournemouth',
        odd: 1.23,
        time: '23:25 11.06.2022',
        isWin: true,
      },
      {
        type: 'soccer',
        teams: ['Queens Park Rangers', 'AFC Bournemouth'],
        wagered: 12,
        on: 'AFC Bournemouth',
        odd: 1.23,
        time: '23:25 11.06.2022',
        isWin: false,
      },
      {
        type: 'soccer',
        teams: ['Queens Park Rangers', 'AFC Bournemouth'],
        wagered: 12,
        on: 'AFC Bournemouth',
        odd: 1.23,
        time: '23:25 11.06.2022',
        isWin: true,
      },
    ],
  ],
};
